"""Assert the block in reference/harvest-block.md matches harvest.py + filters.py.

The skill promises an agent can paste the block and get identical routing. If
the two drift, that promise is false and the spec's numbers stop being
reproducible from what the agent actually runs.

harvest.py imports its format-agnostic filters from filters.py, so a verbatim
copy of harvest.py alone would fail on that import. The block therefore splices
filters.py in AT THE IMPORT SITE rather than concatenating the two files: that
keeps harvest.py's `# /// script` header at the top, where uv needs it, and
leaves the routing code below in its original order.

Usage:  python tests/check_sync.py [--fix]
"""
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
SKILL = ROOT / "skills" / "doc-extract"
SRC = SKILL / "harvest.py"
FILTERS = SKILL / "filters.py"
DOC = SKILL / "reference" / "harvest-block.md"

# The exact line the splice replaces. Asserted rather than pattern-matched: if
# harvest.py's import grows a name and this literal is not updated, the check
# fails loudly instead of silently emitting a block that is missing a symbol.
IMPORT_LINE = ("from filters import (MIN_DIM, MAX_ASPECT, MIN_AREA, UBIQUITY, MAX_EDGE_PX,\n"
               "                     SCALE_GUARD, furniture_reason, _tok)\n")

HEADER = """# harvest-block

Self-contained rendering of `harvest.py`, with `filters.py` spliced in at the
import site, for agents that cannot execute a file. Generated by
`tests/check_sync.py --fix`; do not edit by hand.

```python
"""
FOOTER = "```\n"


def render():
    src = SRC.read_text()
    if IMPORT_LINE not in src:
        raise SystemExit(
            f"harvest.py no longer contains the expected import line:\n"
            f"  {IMPORT_LINE!r}\n"
            f"Update IMPORT_LINE in {Path(__file__).name} to match, so the "
            f"pasted block keeps every symbol harvest.py needs.")
    spliced = src.replace(IMPORT_LINE, FILTERS.read_text(), 1)
    return HEADER + spliced + FOOTER


def main():
    want = render()
    if "--fix" in sys.argv:
        DOC.parent.mkdir(parents=True, exist_ok=True)
        DOC.write_text(want)
        print(f"wrote {DOC.relative_to(ROOT)}")
        return 0
    if not DOC.exists():
        print(f"MISSING: {DOC.relative_to(ROOT)} -- run with --fix")
        return 1
    if DOC.read_text() != want:
        print(f"OUT OF SYNC: {DOC.relative_to(ROOT)} != "
              f"{SRC.relative_to(ROOT)} + {FILTERS.relative_to(ROOT)}")
        print("run: python tests/check_sync.py --fix")
        return 1
    print("in sync")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
